Edited vector specification to accomadate code style
noorbuchi/pygmt pull request #1
Opened 2021-03-19 18:10 UTC by Nathandloria

**Description of proposed changes**

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

2021-03-20 18:52 UTC, noorbuchi requested changes

2021-03-20 18:52 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +data = np.array([[5, 5, 2.5, 90, 270]])
I think it would be nice to create a subheading for circular and geographic vectors. It helps separate the examples for the user specifically looking for a circular vector tutorial.

2021-03-20 18:52 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +# vector specifications structured as: [x_start, y_start, diameter, degree_start, degree_stop]
I just tried running this example, the third element in the list (`2.5` in this case) stands for the radius and not the diameter. I think that the comment should be changed to reflect that. Thanks

2021-03-20 18:52 UTC, noorbuchi commented on examples/tutorials/vectors.py
>  # ``stopDeg`` specify at what angle the arc will begin and end respectively.
Please make sure to change `diam` to `radius` in the description as well

2021-03-20 18:52 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +    color="red3",
There was a recent review on our PR on the main repo about the units of measurement represented by `c` in the projection. The reviewer mentioned that this represents centimeters in this case and we should mention that and include examples of other measurements. I'm not exactly sure but it's probably worth looking through the documentation for that

2021-03-23 02:04 UTC, Nathandloria commented on examples/tutorials/vectors.py
> +    color="red3",
Hi Noor, I think you handled this in your examples, do we think it would be redundant to do this for circular vectors as well? Also, could you link me to that review so I know more of what you mean?

2021-03-23 02:04 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +    color="red3",
I've since figured out what the reviewers wanted us to do with the units of measurement. If possible, please make sure to clearly say that radius uses centimeters by default and provide and example similar to mine where you change the unit to inches

2021-03-23 02:04 UTC, Nathandloria commented on examples/tutorials/vectors.py
>  # ``stopDeg`` specify at what angle the arc will begin and end respectively.
Done

2021-03-23 02:16 UTC, noorbuchi requested changes

2021-03-23 02:16 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +# will begin and end respectively.
Since the old format was removed, there is not variable `radius` anymore. Please update the description to match the new code. Same idea goes for `degree_start` and `degree_stop`. Instead, here is a suggestion:
```suggestion
# Circular vectors can be plotted by creating a list of the vector's attributes
# and passing it into the ``data`` parameter.
#
# The list should be structured as follows:
# ``[x_start, y_start, radius, degree_start, degree_stop]``
# where ``x_start`` and ``y_start`` specify the center of the circle,
# ``radius`` is the radius of the circle in centimeters,
# and ``degree_start`` and ``degree_stop``  specify at what angle (in degrees) the arc
# will begin and end respectively.
```

2021-03-23 02:16 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +data = np.array([[4, 4, 2, 90, 270]])
I think this should be split up into two steps. One for the creation of the simple list and the other for the numpy array

```suggestion
vector_1 = [4, 4, 2, 90, 270]
data = np.array([vector_1])
```

2021-03-23 02:16 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +    projection="X10c/10c",
it might be a good idea for the region and the projection to match in numbers in this first examples, just to keep it simple looking

2021-03-23 02:16 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +    frame="a",
I found that `frame="ag"` creates a more detailed grid that makes the vector easier to see. Try using it and see how it looks like

2021-03-23 02:16 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +    style="m0.5c+ea",
I think it's good to explain that the `m` prefix here determines that it's a circular vector. You should mention that in the description in a separate paragraph

2021-03-23 02:27 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +    color="red3",
This is the [thread](https://github.com/GenericMappingTools/pygmt/pull/1070#discussion_r598083994) that talked about this change. You don't have to provide a full example of using inches but if you could simply mention that the default unit of the radius is centimeters, then that should be fine. Thanks!

2021-03-25 00:49 UTC, noorbuchi approved these changes

2021-03-25 00:57 UTC, Nathandloria commented
Sorry Noor I forgot to push my next example lol.

2021-03-25 01:02 UTC, noorbuchi commented
you're good! no worries

2021-03-25 01:04 UTC, noorbuchi approved these changes

2021-03-25 14:52 UTC, merged