Geographic Vectors Examples
noorbuchi/pygmt pull request #3
Opened 2021-03-24 18:12 UTC by munzekm

Branch to create examples of geographic vectors with pygmt.

2021-03-24 18:55 UTC, noorbuchi requested changes
There are three `Untitled.ipynb` that are not needed. Please make sure to remove those before merging

2021-03-24 20:22 UTC, cklima616 commented
Fixing the import order will get rid of one of those errors.

2021-03-24 20:25 UTC, cklima616 requested changes
Fix the import order and get rid of those Untitled files and it'll be set to merge!

2021-03-25 00:53 UTC, noorbuchi commented
/format

2021-03-25 14:39 UTC, noorbuchi requested changes

2021-03-25 14:39 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +y = [-87.6298, 41.8781]
I think that renaming those variables to `point_1` and `point_2` might be better, in this case, to make it clear that these are not a list of x values and y values similar to how cartesian vectors work

2021-03-25 14:40 UTC, noorbuchi commented on examples/tutorials/vectors.py
> +data = np.array([x + y])
```suggestion
point_1 = [-114.7420, 44.0682]
point_2 = [-87.6298, 41.8781]
data = np.array([point_1 + point_2])
```

2021-03-25 15:04 UTC, merged